# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bc49ed6ac7da1547a111429bd3475d9476f1c821b64602076bfd321b7901350bf2160d40c303d1f9a1c082099c7986b7715288dcf02b801d39c27c21ed5d8a6a

test:
  secret_key_base: d5d1da78e86a0df0f07659e4833d163c56c25923aa5bc5064af4bd08b34ca9099193d01d33c74de17d6f14158efe23195b9fbbf976f2c0c05b2a88fe0dc70c99

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
